add lesson 09 HW1
EduardNovik/Front-End-Pro pull request #10
Opened 2022-11-02 15:42 UTC by EduardNovik

2022-11-02 17:11 UTC, vb-oiko commented on Lesson 09/lesson 09 script1.js
> +    if (this.numberOfHouse > 0 || this.numberOfHouse <= 200) {
в завданні трошки інша вимога

2022-11-02 17:13 UTC, vb-oiko requested changes
клас Будинок 
    властивості 
        масив квартир, який при створенні пустий
        максимальна кількість квартир
    методи
        конструктор, який приймає один параметр: максимальну кількість квартир
        додати квартиру - метод повинен приймати екземпляр класу Квартира, перевіряти, чи не буде кількість перевищувати максимальну кількість квартир, і якщо це так, додати квартиру, в іншому випадку виводить у консоль відповідне повідомлення

2022-11-04 17:58 UTC, EduardNovik commented on Lesson 09/lesson 09 script1.js
> +    if (this.numberOfHouse > 0 || this.numberOfHouse <= 200) {
Я виправив. Дякую за коментар

2022-11-05 08:58 UTC, vb-oiko commented on Lesson 09/lesson 09 script1.js
> +    this.numberOfOccupiedApartments++;
Ви завжди можете перевірити довжину масива квартир

2022-11-05 08:58 UTC, vb-oiko commented on Lesson 09/lesson 09 script1.js
> +  addPerson(people) {
```suggestion
  addResident(resident) {
```

2022-11-05 08:58 UTC, vb-oiko approved these changes

2022-11-09 20:04 UTC, SSSergiy commented on Lesson 09/lesson 09 script1.js
> +
стгсзтгтсгмкдв кдквд

2022-11-09 20:04 UTC, SSSergiy commented on Lesson 09/lesson 09 script1.js
> +
стгтмнгткгтнгт

2022-11-09 20:04 UTC, SSSergiy commented on Lesson 09/lesson 09 script1.js
> +    elem.apartmentResidents.forEach(item => console.log(`Name: ${item.name}, Surname: ${item.surname}, Age: ${item.age}`))
генгем

2022-11-09 20:07 UTC, merged